version: 3

tasks:
  default:
    cmds:
      - echo "Hello, World!"
    deps:
      - build
      - test
      - deploy
  build:
    cmds:
      - echo "Building..."
  test:
    cmds:
      - dotnet test
  deploy:
    cmds:
      - echo "Deploying..."
