version: 3

tasks:
  default:
    cmds:
      - echo "Hello, World!"
    deps:
      - clean
      - restore
      - build
      - test
      - deploy
  clean:
    cmds:
      - dotnet clean

  restore:
    cmds:
      - dotnet restore
  build:
    cmds:
      - dotnet build --no-restore
  test:
    cmds:
      - dotnet test
  run:
    cmds:
      - dotnet run --project src/Eldergrove.Gui/Eldergrove.Gui.csproj
  bump-alpha:
    cmds:
      - versionize --pre-release alpha
      - git push --follow-tags origin main
